---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: sitewhere-manager-role
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
    verbs:
      - create
      - delet
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sitewhere.io
    resources:
      - instances
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sitewhere.io
    resources:
      - instances/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - sitewhere.io
    resources:
      - sitewheremicroservices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sitewhere.io
    resources:
      - sitewheremicroservices/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - sitewhere.io
    resources:
      - sitewheretenantengines
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sitewhere.io
    resources:
      - sitewheretenantengines/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - sitewhere.io
    resources:
      - sitewheretenants
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - sitewhere.io
    resources:
      - sitewheretenants/status
    verbs:
      - get
      - patch
      - update
